version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ../volume_space/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=test
      - GF_SECURITY_ADMIN_PASSWORD=!@StrongTestPwd
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    driver: bridge