version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ../volume_space/grafana:/var/lib/grafana
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge