version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    environment:
      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
      - GITLAB_RUNNER_REGISTRATION_TOKEN=${GITLAB_RUNNER_REGISTRATION_TOKEN}
    volumes:
      - '../volume_space/gitlab/config:/etc/gitlab'
      - '../volume_space/gitlab/logs:/var/log/gitlab'
      - '../volume_space/gitlab/data:/var/opt/gitlab'
    ports:
      - "80:80"
      - "443:443"
      - "22:22"

networks:
  default:
    driver: bridge

volumes:
  gitlab_config:
    driver: local
  gitlab_logs:
    driver: local
  gitlab_data:
    driver: local
