version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: '!@StrongTestPwd'
      POSTGRES_DB: testdb
    volumes:
      - ../volume_space/postgres:/var/lib/postgresql/data
      - ./config:/etc/postgresql
    ports:
      - "5432:5432"
