version: '3.8'

services:
  influxdb_ohlcv:
    image: influxdb:2.7.10
    container_name: influxdb_ohlcv
    ports:
      - "8086:8086"
    volumes:
      - ../volume_space/influxdb2:/var/lib/influxdb2
      - ./config/config.yml:/etc/influxdb2/config.yml:ro
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=test
      - DOCKER_INFLUXDB_INIT_PASSWORD=!@StrongTestPwd
      - DOCKER_INFLUXDB_INIT_ORG=test_org
      - DOCKER_INFLUXDB_INIT_BUCKET=test_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=bH7mK9nR2sT4vX6zA1cE3gF5jL8pQ0wY2dU4fG6hJ9kM
    command: influxd
    restart: always

networks:
  default:
    driver: bridge
