version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis_container
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../volume_space/redis:/data
      - ./config:/usr/local/etc/redis
    ports:
      - "6379:6379"
